### ISSUE TITLE
[Feature request] Disable hotseat if hotseat user has been moderated

### ISSUE THREAD

**Issue by cohan** [DaftLimmy/TwitchPopups#17]
If a hotseat user gets timed out, banned, or has a message deleted we should automatically disable and clear the hotseat

**Comment by DaftLimmy** [comment]
I won't bother with that cos the mod can just do !delete

**Comment by cohan** [comment]
I was thinking it’s more work to do the moderation command and then also !delete - if a mod is acting on something their default reaction is likely a timeout. This means any dodgy text would stay on the screen longer while the mods remember to also do a !delete

I will drop it if this doesn’t convince though
