### ISSUE TITLE
[Discussion] Move configuration to its own file

### ISSUE THREAD

**Issue by cohan** [DaftLimmy/TwitchPopups#21]
If we move the configuration to its own file (e.g. something like configuration.js) we can then keep a configuration-sample.js in the git repository and instruct the user to copy that file to configuration.js and edit it when they first install.

This also means when they update they don't overwrite their configuration each time

Having it as its own file instead of a big wall of text at the top of twitchpopups.htm makes it less imposing for non-coder types and means we can put more options in there. For example maybe one streamer doesn't want to call it a hotseat, there could be `hotseatName = 'the bin'`, `hotseatCommand = '!bin"` config options.

**Comment by DaftLimmy** [comment]
I'm going to keep it in this one file so it's in one place. If I add lots of new stuff, I'll make the other stuff external but I want all this stuff in the main page.
