### ISSUE TITLE
[Discussion] Making it hosted

### ISSUE THREAD

**Issue by cohan** [DaftLimmy/TwitchPopups#30]
MojoChin on the discord suggested that instead of having this as a download, have it hosted like https://daftlimmy.github.io/Swearing-Xylophone/

This way instead of downloading the package, streamers could instead put in their browser source something like

`https://daftlimmy.github.io/TwitchPopups/?channel=Limmy&bgColour=123456`

and they'd have the latest, new, up to date version of the code with just a source refresh

**Comment by DaftLimmy** [comment]
I don't think that'll work well for a lot of cases cos a lot of folk will want to make tweaks locally.
