### ISSUE TITLE
Loading external html

### ISSUE THREAD

**Issue by DaftLimmy** [DaftLimmy/TwitchPopups#37]
I'm maybe overcomplicating things here but I've been thinking of redoing the code that it loads in the animations from external html files.

That way, streamers can do a slight tweak to the main twitchpopups.html file to say which pages are to be loaded in for which commands, and then they can make a separate page for each animation.

Imagine you had a dozen animations, maybe even twenty or thirty. You wouldn't want all those animations coded in the main page would you?

Anyway, I tried it and I ran into one issue after another. 

Before anybody goes ahead and attempts it, what are your thoughts?

**Comment by cohan** [comment]
For a project like this I'd put them all into a file like animations.js and load that in via a `<script src="./animations.js">`

**Comment by DaftLimmy** [comment]
Roughly speaking, what would the process be in creating new divs and so on with an external javascript file? Can anything be done, am I limited only by my imagination?

**Comment by cohan** [comment]
javascript loaded through script src has the same functionality as inline javascript aye, it's just put in a separate file to make things cleaner

If Slugworth wants a gobstopper, he can have one

**Comment by DaftLimmy** [comment]
I see, I see.

**Comment by monkehhhhh** [comment]
Bit of discussion in the Discord too today about ways to split things up to make it more manageable for developers and usable for streamers which includes this kind of thing too. One idea:

main.htm
main.js -- triggers ticks and on message but only really calls the handlers
settings.js -- holds constants bg colours etc
handlers folder
--| alert.js
--| hotseat.js
--| new handlers added here
--| animation.js
styles folder
--| main.css -- holds base css styles
--| animations.css

.. this would probably be a good opportunity to also do some general clean-up on formatting, comments, indentation, etc.

**Comment by insin** [comment]
It's easier to generate HTML from other JavaScript files with something like [`Element.insertAdjacentHTML()`](https://developer.mozilla.org/en-US/docs/Web/API/Element/insertAdjacentHTML) (or have other files provide HTML as a string for the main page to insert), as `iframes` are a ballache in terms of communication.

Here's an example of alerts being defined in its own file, then hotseats added in a different files, where hotseats reuses the animation created by alerts:

https://codesandbox.io/s/twitchpopups-modules-0zx5w

`tmi.min.js` seems to make CodeSandbox brick itself every other time I open it, so here's a separate version too if that won't run: https://twitchpopups-modules.netlify.app/

**Comment by FunkotronKing** [comment]
> Bit of discussion in the Discord too today about ways to split things up to make it more manageable for developers and usable for streamers which includes this kind of thing too. One idea:
> 
> main.htm
> main.js -- triggers ticks and on message but only really calls the handlers
> settings.js -- holds constants bg colours etc
> handlers folder
> --| alert.js
> --| hotseat.js
> --| new handlers added here
> --| animation.js
> styles folder
> --| main.css -- holds base css styles
> --| animations.css
> 
> .. this would probably be a good opportunity to also do some general clean-up on formatting, comments, indentation, etc.

I have the following: https://github.com/FunkotronKing/TwitchPopups/tree/feature/moduler-structure

Its early days but appears to be working, I want to get the animation code from Gantee and see how it fits with this structure.
