### ISSUE TITLE
HELP: load anims into iframe

### ISSUE THREAD

**Issue by DaftLimmy** [DaftLimmy/TwitchPopups#42]
I NEED YOUR HELP! I've talked about this before, but I've created a new branch called load-anims-into-iframe, and the mission is to load the animations into an iframe. 

Why?

So that the streamer can create various html pages with animations and popups of every description without cluttering the main twitchpopups.html page.

By doing it that way, I think it'll be more straightforward for the streamer (e.g. me) to create each animation page independently, test it more easily, not worry about css conflicts and so on. And they can receive variables either through GET or localstorage or some other method.

I've attempted it myself and it works alright, but the animations sometimes stutter when I load in the page, even though I've got them running after onload. Don't know why.

Anyway, I'D APPRECIATE YOUR HELP.

Feel free to tell me if you think it's a bad idea.

**Comment by Gantonator** [comment]
I think what's happening is that maybe there are calls to external resources (like the google font or whatever) in the animation.html that is being loaded in which the `iframe ` is loading up separately.

Is that right?

So using iframes does preclude you from using external resources in the modular files.  using `$("#someDiv").load("animation.html")` is probably a better but less compatible solution (cause chrome doesn't like cross resource local requests).

If css animations not repeating is the blocker for using `$("#someDiv").load("animation.html")` rather than an `iframe` then the solution is to do 
```
$("#someDiv").empty();
void $("#someDiv")[0].offsetWidth;
$("#someDiv").load("animation.html")
```

between animations.  Then loaded in things like animation.html will be affected by styles/fonts/js/whatever in the main file

**Comment by Gantonator** [comment]
Doing `$("#someDiv").load("animation.html")` does open up space for CSS conflicts but if the `<style>` tags for the animation are in the separate modular `animation.html` file then they will be removed by `$("#someDiv").empty();`.  Which isn't perfect but is worth saying.

**Comment by DaftLimmy** [comment]
Lovely, thanks, I'll try that.

**Comment by FunkotronKing** [comment]
@DaftLimmy I have a solution in my fork based on what I think you are looking for: https://github.com/FunkotronKing/TwitchPopups/tree/feature/moduler-structure

I have done a merge with yours this morning so I have implemented @Gantonator s changes on emotes

I have also taken a few liberties and performed the same modularisation with the command files.
This would make it far easier for you to review as you will be able to see the context for peoples changes.

I have also moved all of the old doAnimation type functions to a generic helper that should make is much easier to remove JQuery as tits only used in one file.

If you like what I have done, I will do some detailed documentation to go through how animators can add new animations and devs can add new handlers etc.

**Comment by FunkotronKing** [comment]
Also worth mentioning if you are not into the restructure I can easily copy paste the !anim functionality into the old structure.

**Comment by DaftLimmy** [comment]
Thanks, looks good, could you do a pull request with my load-anims-into-iframe branch?

Very excited about the possibilities! It's going to ruin my stream!

**Comment by FunkotronKing** [comment]
@DaftLimmy Would you prefer it directly into your master? or do you have work in your branch that you want to keep?

**Comment by FunkotronKing** [comment]
@DaftLimmy Sorted: https://github.com/DaftLimmy/TwitchPopups/pull/43 Let me know if you have any issues or need a hand integrating it
