### ISSUE TITLE
[Suggestion] Move the consts (twitch channel, twitch emotes etc.) to config or .env file

### ISSUE THREAD

**Issue by PolarisNeo** [DaftLimmy/TwitchPopups#44]
This will prevent mistakes where someone forgets to change their channel name back after committing their changes. Would be useful to prevent a rare case of abuse or just any time wasted figuring out why the commands aren't working only to find out it was someone elses channel in the const.

Moving these constants into a .env file or web.config setup will mean no live config file will need to be committed. Instead a .env.example file pulled on first instance with example variables which can be copied into a .env and populated with the user's preferred details.

The .env/config file can be added to a .gitignore preventing anybody from accidentally leaving their channel details or preferences committed (e.g. colors etc.). Will save time on having to keep track of what constants have been changed on every commit.

I can add this if wanted.

**Comment by cohan** [comment]
Duplicate of #21

**Comment by PolarisNeo** [comment]
Seems like this has been implemented (in a way) with the addition of settings.js. Good stuff!
