### ISSUE TITLE
[Feature request] Display last 5 messages of the user

### ISSUE THREAD

**Issue by rnsc** [DaftLimmy/TwitchPopups#7]
Would be nice to have the latest message bottom, but then, above it, the last 4 messages in a smaller font.

While doing that, maybe when activating the hotseat, we can already display the last message (which is likely the one that triggered the hotseat activation) of the user instead of waiting for a new message.

**Comment by DaftLimmy** [comment]
Thanks. I don't think I'll do that, though, just to keep it simple.
